"""Leaf hashing — the frozen action leaf (v1) and the receipt leaf (v1).

Every hashed structure carries a domain tag as its first bytes, so a digest from
one structure can never be read as a digest from another, and a v2 can exist
beside a v1 without ambiguity.

``merkl-leaf-v1`` is **frozen** (``merkl-api/docs/SPEC.md`` section 2). The
function here is the same encoding as ``merkl_api.action.hashing.compute_leaf_hash``,
lifted off ``ActionRecord`` so it takes plain fields and the SDK can compute an
action leaf without the server's ORM. ``tests/core/test_action_leaf_identity.py``
pins it byte-for-byte against hashes generated by merkl-api's own code.

``merkl-receipt-leaf-v1`` is new in this phase: one leaf of a co-signer receipt.
"""

from __future__ import annotations

from collections.abc import Sequence
from datetime import datetime
from typing import Any

from merkl.core.canonical import ensure_canonical_content, hex_digest
from merkl.shared.errors import ValidationError
from merkl.shared.hashing import SHA256Hash, canonical_bytes

NUL = b"\x00"

ACTION_LEAF_TAG = b"merkl-leaf-v1"
"""Frozen domain tag of the session action leaf (SPEC.md section 2)."""

RECEIPT_LEAF_TAG = b"merkl-receipt-leaf-v1"
"""Domain tag of a co-signer receipt leaf."""


def _hash_hex(value: SHA256Hash | str, *, field: str) -> str:
    """Normalize a hash argument to the lowercase hex the leaf encoding uses."""
    if isinstance(value, SHA256Hash):
        return value.hex()
    return hex_digest(value, field)


def action_leaf(
    *,
    action_id: str,
    session_id: str,
    action_type: str,
    tool_name: str,
    input_hash: SHA256Hash | str,
    output_hash: SHA256Hash | str,
    timestamp: datetime | str,
    drift_score: float | str,
    guardrail_result: str,
    display_name: str = "",
    depends_on: Sequence[str] = (),
    status: str = "success",
    category: str = "",
) -> SHA256Hash:
    """Compute the frozen ``merkl-leaf-v1`` action leaf from plain fields.

    ``leaf = SHA-256("merkl-leaf-v1" || NUL || action_id || NUL || session_id ||
    NUL || action_type || NUL || tool_name || NUL || input_hash_hex || NUL ||
    output_hash_hex || NUL || timestamp_iso || NUL || drift_score_str || NUL ||
    guardrail_result || NUL || display_name || NUL || depends_on_sorted_csv ||
    NUL || status || NUL || category)``

    Encoding notes, all of them load-bearing:

    * text is UTF-8; ``NUL`` is one 0x00 byte and also follows the domain tag;
    * ``input_hash`` / ``output_hash`` are lowercase hex, not raw digests;
    * ``timestamp`` is ``datetime.isoformat()`` of the action timestamp — pass the
      exact string if you have one, since ``isoformat()`` drops a zero microsecond
      field and a verifier must not re-derive it;
    * ``drift_score`` is Python's ``str()`` of the float (``0.0`` renders ``"0.0"``,
      not ``"0"``). Pass a string to reproduce a leaf exactly in another runtime;
    * ``depends_on`` is lexicographically sorted and joined with ``","``;
    * previews are excluded on purpose, so the leaf recomputes without access to
      hidden data.

    Enum members (``ActionType``, ``GuardrailResult``, ``ActionStatus``) are
    ``StrEnum`` and may be passed directly wherever a ``str`` is accepted.
    """
    timestamp_iso = timestamp.isoformat() if isinstance(timestamp, datetime) else timestamp
    drift = drift_score if isinstance(drift_score, str) else str(drift_score)

    parts: list[bytes] = [
        str(action_id).encode(),
        str(session_id).encode(),
        str(action_type).encode(),
        tool_name.encode(),
        _hash_hex(input_hash, field="input_hash").encode(),
        _hash_hex(output_hash, field="output_hash").encode(),
        timestamp_iso.encode(),
        drift.encode(),
        str(guardrail_result).encode(),
        display_name.encode(),
        ",".join(sorted(depends_on)).encode(),
        str(status).encode(),
        category.encode(),
    ]
    return SHA256Hash.from_bytes(ACTION_LEAF_TAG + NUL + NUL.join(parts))


def receipt_leaf(name: str, content: Any) -> SHA256Hash:
    """Compute a ``merkl-receipt-leaf-v1`` leaf hash.

    ``leaf = SHA-256("merkl-receipt-leaf-v1" || NUL || leaf_name || NUL ||
    canonical_bytes(content))``

    ``leaf_name`` is UTF-8 and is one of the seven names in
    :data:`merkl.core.receipt.LEAF_NAMES`; binding it into the hash is what stops
    two leaves being swapped without changing the tree. Absent content is the
    literal JSON ``null`` (``canonical_bytes(None) == b"null"``), so a receipt
    with no attestation still commits to *having* no attestation.

    ``content`` must be canonical receipt content (see
    :func:`merkl.core.canonical.ensure_canonical_content`): no floats anywhere.
    """
    if not name:
        raise ValidationError("Receipt leaf name cannot be empty")
    ensure_canonical_content(content)
    return SHA256Hash.from_bytes(
        RECEIPT_LEAF_TAG + NUL + name.encode() + NUL + canonical_bytes(content)
    )
